import type { ToolCategorySlug, ToolDefinition } from "@/lib/types";

export const tools: ToolDefinition[] = [
  {
    slug: "csv-to-json",
    title: "CSV to JSON Converter",
    shortDescription: "Convert CSV rows into JSON objects instantly.",
    tags: ["csv", "json", "converter", "spreadsheet", "data transformation"],
    intro: "Convert comma-separated values into structured JSON for APIs and JavaScript apps.",
    howToUse: [
      "Paste CSV with headers in the first row.",
      "Click Transform to generate JSON.",
      "Copy output or download the JSON file.",
    ],
    exampleInput: "name,email\nAna,ana@example.com",
    exampleOutput: '[\n  {\n    "name": "Ana",\n    "email": "ana@example.com"\n  }\n]',
    whyUseful: "Great for moving spreadsheet data into web apps quickly.",
    faq: [
      { question: "Does this support headers?", answer: "Yes. First CSV row is used as object keys." },
      { question: "Can I download output?", answer: "Yes, download button exports JSON." },
    ],
    related: ["json-formatter", "csv-cleaner", "json-validator"],
    kind: "standard",
    categories: ["csv-tools", "json-tools", "spreadsheet-tools"],
    createdAt: "2026-03-01",
    outputFileName: "converted.json",
    outputMimeType: "application/json",
  },
  {
    slug: "json-to-csv",
    title: "JSON to CSV Converter",
    shortDescription: "Turn JSON arrays into CSV for spreadsheets.",
    tags: ["json", "csv", "converter", "spreadsheet", "export"],
    intro: "Convert JSON arrays of objects into CSV format compatible with Excel and Sheets.",
    howToUse: ["Paste JSON array.", "Click Transform.", "Copy or download CSV."],
    exampleInput: '[{"name":"Ana","email":"ana@example.com"}]',
    exampleOutput: "name,email\nAna,ana@example.com",
    whyUseful: "Useful for exporting API data to spreadsheet workflows.",
    faq: [
      { question: "What JSON shape is expected?", answer: "A non-empty array of objects." },
      { question: "Are missing keys handled?", answer: "Yes. Missing values are left empty." },
    ],
    related: ["csv-to-json", "json-minifier", "csv-validator"],
    kind: "standard",
    categories: ["csv-tools", "json-tools", "spreadsheet-tools"],
    createdAt: "2026-03-02",
    outputFileName: "converted.csv",
    outputMimeType: "text/csv",
  },
  {
    slug: "csv-cleaner",
    title: "CSV Cleaner",
    shortDescription: "Trim spaces and remove empty rows from CSV.",
    tags: ["csv", "cleaner", "data cleanup", "spreadsheet"],
    intro: "Clean messy CSV files by trimming cells and dropping blank rows.",
    howToUse: ["Paste CSV.", "Click Transform.", "Download cleaned CSV."],
    exampleInput: "name,email\n Ana , ana@example.com \n,",
    exampleOutput: "name,email\nAna,ana@example.com",
    whyUseful: "Prepares data before imports and analysis.",
    faq: [
      { question: "Will this remove columns?", answer: "No. It keeps original column structure." },
      { question: "Does it trim all cells?", answer: "Yes, leading/trailing spaces are removed." },
    ],
    related: ["csv-validator", "csv-to-json", "json-to-csv"],
    kind: "standard",
    categories: ["csv-tools", "spreadsheet-tools"],
    createdAt: "2026-03-03",
    outputFileName: "cleaned.csv",
    outputMimeType: "text/csv",
  },
  {
    slug: "csv-validator",
    title: "CSV Validator",
    shortDescription: "Check CSV structure for inconsistent rows.",
    tags: ["csv", "validator", "data quality", "spreadsheet"],
    intro: "Validate that each CSV row has the same number of columns.",
    howToUse: ["Paste CSV text.", "Click Transform to validate.", "Review validation result."],
    exampleInput: "name,email\nAna,ana@example.com\nBob",
    exampleOutput: "CSV has structural issues:\nRow 3: expected 2 columns, found 1.",
    whyUseful: "Finds import-breaking CSV problems quickly.",
    faq: [
      { question: "Does it validate data types?", answer: "No, it validates CSV structure." },
      { question: "Will it report row numbers?", answer: "Yes, each issue includes the row number." },
    ],
    related: ["csv-cleaner", "csv-to-json", "json-validator"],
    kind: "standard",
    categories: ["csv-tools", "spreadsheet-tools"],
    createdAt: "2026-03-04",
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    shortDescription: "Beautify JSON with indentation.",
    tags: ["json", "formatter", "beautify", "developer"],
    intro: "Format minified or compact JSON into readable structure.",
    howToUse: ["Paste JSON.", "Click Transform.", "Copy formatted JSON."],
    exampleInput: '{"name":"Ana","active":true}',
    exampleOutput: '{\n  "name": "Ana",\n  "active": true\n}',
    whyUseful: "Improves readability and debugging speed.",
    faq: [
      { question: "Does this validate JSON too?", answer: "Yes. Invalid JSON returns an error." },
      { question: "Will key order change?", answer: "No, existing key order is preserved." },
    ],
    related: ["json-validator", "json-minifier", "csv-to-json"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-05",
  },
  {
    slug: "json-validator",
    title: "JSON Validator",
    shortDescription: "Validate JSON syntax instantly.",
    tags: ["json", "validator", "syntax", "developer"],
    intro: "Check whether your JSON is syntactically valid before using it.",
    howToUse: ["Paste JSON.", "Click Transform.", "Read validation result."],
    exampleInput: '{"name":"Ana"}',
    exampleOutput: "Valid JSON.",
    whyUseful: "Prevents parser errors in code and APIs.",
    faq: [
      { question: "Do you fix invalid JSON?", answer: "No, this tool validates and reports errors." },
      { question: "Can large files be checked?", answer: "Yes, if your browser can load them." },
    ],
    related: ["json-formatter", "json-minifier", "csv-to-json"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-06",
  },
  {
    slug: "json-minifier",
    title: "JSON Minifier",
    shortDescription: "Compress JSON by removing whitespace.",
    tags: ["json", "minifier", "compress", "developer"],
    intro: "Minify JSON payloads for faster transfer and smaller file size.",
    howToUse: ["Paste JSON.", "Click Transform.", "Copy or download minified output."],
    exampleInput: '{\n  "name": "Ana"\n}',
    exampleOutput: '{"name":"Ana"}',
    whyUseful: "Reduces payload sizes in APIs and configs.",
    faq: [
      { question: "Does it change data?", answer: "No, only formatting whitespace is removed." },
      { question: "Can I download output?", answer: "Yes. Download as JSON is supported." },
    ],
    related: ["json-formatter", "json-validator", "json-to-csv"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-07",
    outputFileName: "minified.json",
    outputMimeType: "application/json",
  },
  {
    slug: "remove-duplicate-lines",
    title: "Remove Duplicate Lines",
    shortDescription: "Keep unique lines while preserving order.",
    tags: ["text", "duplicate", "cleanup", "lines"],
    intro: "Delete repeated lines from text and keep first occurrences.",
    howToUse: ["Paste text with one item per line.", "Click Transform.", "Copy deduplicated text."],
    exampleInput: "apple\nbanana\napple",
    exampleOutput: "apple\nbanana",
    whyUseful: "Useful for cleaning lists, tags, and logs.",
    faq: [
      { question: "Is original order preserved?", answer: "Yes. First appearance order is kept." },
      { question: "Case-sensitive?", answer: "Yes. 'A' and 'a' are treated as different lines." },
    ],
    related: ["sort-lines-alphabetically", "extract-emails", "extract-numbers"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-08",
  },
  {
    slug: "sort-lines-alphabetically",
    title: "Sort Lines Alphabetically",
    shortDescription: "Sort multiline text in alphabetical order.",
    tags: ["text", "sort", "alphabetical", "lines"],
    intro: "Order lines A-Z for easier review and deduplication.",
    howToUse: ["Paste lines.", "Click Transform.", "Copy sorted result."],
    exampleInput: "zebra\napple\nBanana",
    exampleOutput: "apple\nBanana\nzebra",
    whyUseful: "Useful for organizing keywords, names, and IDs.",
    faq: [
      { question: "Is sorting case-sensitive?", answer: "Sorting is case-insensitive." },
      { question: "Will blank lines stay?", answer: "Yes, blank lines are included in sorting." },
    ],
    related: ["remove-duplicate-lines", "extract-emails", "extract-numbers"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-09",
  },
  {
    slug: "extract-emails",
    title: "Extract Emails from Text",
    shortDescription: "Find and list emails from any text block.",
    tags: ["text", "email", "extract", "parser"],
    intro: "Extract email addresses from logs, documents, or pasted content.",
    howToUse: ["Paste text.", "Click Transform.", "Copy extracted email list."],
    exampleInput: "Contact ana@example.com or bob@site.io",
    exampleOutput: "ana@example.com\nbob@site.io",
    whyUseful: "Speeds up lead cleanup and data extraction tasks.",
    faq: [
      { question: "Are duplicates removed?", answer: "Yes. Output includes unique addresses." },
      { question: "What if none found?", answer: "Tool returns 'No emails found.'" },
    ],
    related: ["extract-numbers", "remove-duplicate-lines", "sort-lines-alphabetically"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-10",
  },
  {
    slug: "extract-numbers",
    title: "Extract Numbers from Text",
    shortDescription: "Pull numeric values from mixed text.",
    tags: ["text", "numbers", "extract", "parser"],
    intro: "Extract decimals and integers from paragraphs, logs, or notes.",
    howToUse: ["Paste text.", "Click Transform.", "Copy extracted numbers."],
    exampleInput: "Order 102, price 49.95, qty 3",
    exampleOutput: "102\n49.95\n3",
    whyUseful: "Quickly isolate numeric values for analysis.",
    faq: [
      { question: "Does it support decimals?", answer: "Yes. Decimal values are extracted." },
      { question: "Are negative numbers supported?", answer: "Yes." },
    ],
    related: ["extract-emails", "remove-duplicate-lines", "sort-lines-alphabetically"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-11",
  },
  {
    slug: "base64-encoder",
    title: "Base64 Encoder",
    shortDescription: "Encode plain text into Base64 format.",
    tags: ["base64", "encoder", "developer", "text"],
    intro: "Convert regular text input into Base64 for transport, tokens, and quick debugging.",
    howToUse: ["Paste plain text.", "Click Transform.", "Copy the Base64 output."],
    exampleInput: "hello world",
    exampleOutput: "aGVsbG8gd29ybGQ=",
    whyUseful: "Useful when APIs or tools require Base64-encoded text payloads.",
    faq: [
      { question: "Does this support Unicode text?", answer: "Yes. Unicode text is encoded safely." },
      { question: "Can I encode multiline text?", answer: "Yes. Newlines are preserved in encoding." },
    ],
    related: ["base64-decoder", "url-encoder", "uuid-generator"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-12",
  },
  {
    slug: "base64-decoder",
    title: "Base64 Decoder",
    shortDescription: "Decode Base64 content back into readable text.",
    tags: ["base64", "decoder", "developer", "text"],
    intro: "Decode Base64 strings into plain text for inspection and debugging.",
    howToUse: ["Paste Base64 input.", "Click Transform.", "Copy decoded text output."],
    exampleInput: "aGVsbG8gd29ybGQ=",
    exampleOutput: "hello world",
    whyUseful: "Quickly inspect encoded values from APIs, logs, and payloads.",
    faq: [
      { question: "Why does decoding fail?", answer: "Input must be valid Base64 with proper padding." },
      { question: "Can I decode URL-safe Base64?", answer: "Standard Base64 input is expected." },
    ],
    related: ["base64-encoder", "url-decoder", "json-formatter"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-13",
  },
  {
    slug: "uuid-generator",
    title: "UUID Generator",
    shortDescription: "Generate random UUID v4 identifiers instantly.",
    tags: ["uuid", "generator", "developer", "ids"],
    intro: "Generate one or more UUID v4 values for database keys, test data, or API payloads.",
    howToUse: [
      "Leave input empty to generate one UUID.",
      "Optionally enter a number from 1 to 100 to generate multiple UUIDs.",
      "Click Transform and copy the output list.",
    ],
    exampleInput: "3",
    exampleOutput:
      "3f0b7f2d-7378-4f6c-a2d8-2b7c1d9f0e55\n7f854ec9-fbaf-4db4-9b89-3c6bfa42a4f1\n2146efdf-4a5e-4ec8-98e7-f4291f652d06",
    whyUseful: "Saves time when you need valid UUIDs for test records and integrations.",
    faq: [
      { question: "Which UUID version is generated?", answer: "This tool generates UUID version 4 values." },
      { question: "Can I generate many IDs at once?", answer: "Yes, enter a number up to 100." },
    ],
    related: ["base64-encoder", "url-encoder", "json-formatter"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-14",
  },
  {
    slug: "url-encoder",
    title: "URL Encoder",
    shortDescription: "Encode text for safe use in URL query strings.",
    tags: ["url", "encoder", "developer", "query string"],
    intro: "Encode reserved characters so text can be safely used in URLs and query parameters.",
    howToUse: ["Paste text.", "Click Transform.", "Copy encoded URL text."],
    exampleInput: "name=John Doe&city=New York",
    exampleOutput: "name%3DJohn%20Doe%26city%3DNew%20York",
    whyUseful: "Prevents URL-breaking characters from causing request and parsing issues.",
    faq: [
      { question: "When should I URL-encode text?", answer: "Encode text before placing it in query parameters." },
      { question: "Why are spaces changed?", answer: "Spaces are encoded to keep URLs valid and unambiguous." },
    ],
    related: ["url-decoder", "base64-encoder", "json-formatter"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-15",
  },
  {
    slug: "url-decoder",
    title: "URL Decoder",
    shortDescription: "Decode URL-encoded strings into readable text.",
    tags: ["url", "decoder", "developer", "query string"],
    intro: "Convert encoded URL strings back to human-readable text for debugging and analysis.",
    howToUse: ["Paste URL-encoded text.", "Click Transform.", "Copy decoded output."],
    exampleInput: "name%3DJohn%20Doe%26city%3DNew%20York",
    exampleOutput: "name=John Doe&city=New York",
    whyUseful: "Makes encoded query strings and logs easier to inspect and troubleshoot.",
    faq: [
      { question: "What if decoding fails?", answer: "Input may contain malformed percent-encoding." },
      { question: "Does this decode full URLs?", answer: "Yes, encoded URL strings and query values are supported." },
    ],
    related: ["url-encoder", "base64-decoder", "extract-emails"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-16",
  },
  {
    slug: "regex-tester",
    title: "Regex Tester",
    shortDescription: "Test regular expressions against sample text instantly.",
    tags: ["regex", "tester", "developer", "pattern matching"],
    intro:
      "Validate regular expression patterns and quickly inspect matching results using your own input text.",
    howToUse: [
      "Enter the regex on the first line using /pattern/flags format, or plain pattern text.",
      "Add the test text on the following lines.",
      "Click Transform to view match count and matched values.",
    ],
    exampleInput: "/\\b\\w{4}\\b/g\nThis line has many word tokens in text.",
    exampleOutput:
      "Pattern: /\\b\\w{4}\\b/g\nTotal matches: 5\nMatches:\n1. This\n2. line\n3. many\n4. word\n5. text",
    whyUseful:
      "Helps developers debug and validate regex patterns before using them in code, filters, or search logic.",
    faq: [
      { question: "Can I use regex flags?", answer: "Yes. Use /pattern/flags syntax such as /test/gi." },
      { question: "Does it show all matches?", answer: "Yes, it reports total matches and each matched value." },
    ],
    related: ["extract-emails", "extract-numbers", "json-validator"],
    kind: "standard",
    categories: ["developer-tools", "text-tools"],
    createdAt: "2026-03-17",
  },
  {
    slug: "timestamp-converter",
    title: "Timestamp Converter",
    shortDescription: "Convert Unix timestamps and date strings into readable time formats.",
    tags: ["timestamp", "converter", "unix", "date", "developer"],
    intro:
      "Convert Unix seconds, Unix milliseconds, or date strings into UTC, local time, and normalized timestamp output.",
    howToUse: [
      "Paste a Unix timestamp (seconds or milliseconds) or a date string.",
      "Click Transform to convert it.",
      "Review UTC, local time, and Unix equivalents.",
    ],
    exampleInput: "1710000000",
    exampleOutput:
      '{\n  "input": "1710000000",\n  "unixSeconds": 1710000000,\n  "unixMilliseconds": 1710000000000,\n  "utc": "2024-03-09T16:00:00.000Z"\n}',
    whyUseful:
      "Useful for debugging API payloads, logs, analytics events, and systems that store Unix timestamps.",
    faq: [
      { question: "Does it support seconds and milliseconds?", answer: "Yes, both Unix seconds and milliseconds are supported." },
      { question: "Can I convert date strings too?", answer: "Yes, standard date strings can be parsed and converted." },
    ],
    related: ["json-formatter", "uuid-generator", "url-decoder"],
    kind: "standard",
    categories: ["developer-tools"],
    createdAt: "2026-03-18",
  },
];

export const toolsBySlug = Object.fromEntries(tools.map((tool) => [tool.slug, tool]));

export const toolsByCategory = (category: ToolCategorySlug): ToolDefinition[] =>
  tools.filter((tool) => tool.categories.includes(category));

export const recentTools = (limit = 6): ToolDefinition[] =>
  [...tools]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
