import type { ToolCategorySlug, ToolDefinition } from "@/lib/types";

export const tools: ToolDefinition[] = [
  {
    slug: "csv-to-json",
    title: "CSV to JSON Converter",
    shortDescription: "Convert CSV rows into JSON objects instantly.",
    tags: ["csv", "json", "converter", "spreadsheet", "data transformation"],
    intro: "Convert comma-separated values into structured JSON for APIs and JavaScript apps.",
    howToUse: [
      "Paste CSV with headers in the first row.",
      "Click Transform to generate JSON.",
      "Copy output or download the JSON file.",
    ],
    exampleInput: "name,email\nAna,ana@example.com",
    exampleOutput: '[\n  {\n    "name": "Ana",\n    "email": "ana@example.com"\n  }\n]',
    whyUseful: "Great for moving spreadsheet data into web apps quickly.",
    faq: [
      { question: "Does this support headers?", answer: "Yes. First CSV row is used as object keys." },
      { question: "Can I download output?", answer: "Yes, download button exports JSON." },
    ],
    related: ["json-formatter", "csv-cleaner", "json-validator"],
    kind: "standard",
    categories: ["csv-tools", "json-tools", "spreadsheet-tools"],
    createdAt: "2026-03-01",
    outputFileName: "converted.json",
    outputMimeType: "application/json",
  },
  {
    slug: "json-to-csv",
    title: "JSON to CSV Converter",
    shortDescription: "Turn JSON arrays into CSV for spreadsheets.",
    tags: ["json", "csv", "converter", "spreadsheet", "export"],
    intro: "Convert JSON arrays of objects into CSV format compatible with Excel and Sheets.",
    howToUse: ["Paste JSON array.", "Click Transform.", "Copy or download CSV."],
    exampleInput: '[{"name":"Ana","email":"ana@example.com"}]',
    exampleOutput: "name,email\nAna,ana@example.com",
    whyUseful: "Useful for exporting API data to spreadsheet workflows.",
    faq: [
      { question: "What JSON shape is expected?", answer: "A non-empty array of objects." },
      { question: "Are missing keys handled?", answer: "Yes. Missing values are left empty." },
    ],
    related: ["csv-to-json", "json-minifier", "csv-validator"],
    kind: "standard",
    categories: ["csv-tools", "json-tools", "spreadsheet-tools"],
    createdAt: "2026-03-02",
    outputFileName: "converted.csv",
    outputMimeType: "text/csv",
  },
  {
    slug: "csv-cleaner",
    title: "CSV Cleaner",
    shortDescription: "Trim spaces and remove empty rows from CSV.",
    tags: ["csv", "cleaner", "data cleanup", "spreadsheet"],
    intro: "Clean messy CSV files by trimming cells and dropping blank rows.",
    howToUse: ["Paste CSV.", "Click Transform.", "Download cleaned CSV."],
    exampleInput: "name,email\n Ana , ana@example.com \n,",
    exampleOutput: "name,email\nAna,ana@example.com",
    whyUseful: "Prepares data before imports and analysis.",
    faq: [
      { question: "Will this remove columns?", answer: "No. It keeps original column structure." },
      { question: "Does it trim all cells?", answer: "Yes, leading/trailing spaces are removed." },
    ],
    related: ["csv-validator", "csv-to-json", "json-to-csv"],
    kind: "standard",
    categories: ["csv-tools", "spreadsheet-tools"],
    createdAt: "2026-03-03",
    outputFileName: "cleaned.csv",
    outputMimeType: "text/csv",
  },
  {
    slug: "csv-validator",
    title: "CSV Validator",
    shortDescription: "Check CSV structure for inconsistent rows.",
    tags: ["csv", "validator", "data quality", "spreadsheet"],
    intro: "Validate that each CSV row has the same number of columns.",
    howToUse: ["Paste CSV text.", "Click Transform to validate.", "Review validation result."],
    exampleInput: "name,email\nAna,ana@example.com\nBob",
    exampleOutput: "CSV has structural issues:\nRow 3: expected 2 columns, found 1.",
    whyUseful: "Finds import-breaking CSV problems quickly.",
    faq: [
      { question: "Does it validate data types?", answer: "No, it validates CSV structure." },
      { question: "Will it report row numbers?", answer: "Yes, each issue includes the row number." },
    ],
    related: ["csv-cleaner", "csv-to-json", "json-validator"],
    kind: "standard",
    categories: ["csv-tools", "spreadsheet-tools"],
    createdAt: "2026-03-04",
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    shortDescription: "Beautify JSON with indentation.",
    tags: ["json", "formatter", "beautify", "developer"],
    intro: "Format minified or compact JSON into readable structure.",
    howToUse: ["Paste JSON.", "Click Transform.", "Copy formatted JSON."],
    exampleInput: '{"name":"Ana","active":true}',
    exampleOutput: '{\n  "name": "Ana",\n  "active": true\n}',
    whyUseful: "Improves readability and debugging speed.",
    faq: [
      { question: "Does this validate JSON too?", answer: "Yes. Invalid JSON returns an error." },
      { question: "Will key order change?", answer: "No, existing key order is preserved." },
    ],
    related: ["json-validator", "json-minifier", "csv-to-json"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-05",
  },
  {
    slug: "json-validator",
    title: "JSON Validator",
    shortDescription: "Validate JSON syntax instantly.",
    tags: ["json", "validator", "syntax", "developer"],
    intro: "Check whether your JSON is syntactically valid before using it.",
    howToUse: ["Paste JSON.", "Click Transform.", "Read validation result."],
    exampleInput: '{"name":"Ana"}',
    exampleOutput: "Valid JSON.",
    whyUseful: "Prevents parser errors in code and APIs.",
    faq: [
      { question: "Do you fix invalid JSON?", answer: "No, this tool validates and reports errors." },
      { question: "Can large files be checked?", answer: "Yes, if your browser can load them." },
    ],
    related: ["json-formatter", "json-minifier", "csv-to-json"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-06",
  },
  {
    slug: "json-minifier",
    title: "JSON Minifier",
    shortDescription: "Compress JSON by removing whitespace.",
    tags: ["json", "minifier", "compress", "developer"],
    intro: "Minify JSON payloads for faster transfer and smaller file size.",
    howToUse: ["Paste JSON.", "Click Transform.", "Copy or download minified output."],
    exampleInput: '{\n  "name": "Ana"\n}',
    exampleOutput: '{"name":"Ana"}',
    whyUseful: "Reduces payload sizes in APIs and configs.",
    faq: [
      { question: "Does it change data?", answer: "No, only formatting whitespace is removed." },
      { question: "Can I download output?", answer: "Yes. Download as JSON is supported." },
    ],
    related: ["json-formatter", "json-validator", "json-to-csv"],
    kind: "standard",
    categories: ["json-tools", "developer-tools"],
    createdAt: "2026-03-07",
    outputFileName: "minified.json",
    outputMimeType: "application/json",
  },
  {
    slug: "remove-duplicate-lines",
    title: "Remove Duplicate Lines",
    shortDescription: "Keep unique lines while preserving order.",
    tags: ["text", "duplicate", "cleanup", "lines"],
    intro: "Delete repeated lines from text and keep first occurrences.",
    howToUse: ["Paste text with one item per line.", "Click Transform.", "Copy deduplicated text."],
    exampleInput: "apple\nbanana\napple",
    exampleOutput: "apple\nbanana",
    whyUseful: "Useful for cleaning lists, tags, and logs.",
    faq: [
      { question: "Is original order preserved?", answer: "Yes. First appearance order is kept." },
      { question: "Case-sensitive?", answer: "Yes. 'A' and 'a' are treated as different lines." },
    ],
    related: ["sort-lines-alphabetically", "extract-emails", "extract-numbers"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-08",
  },
  {
    slug: "sort-lines-alphabetically",
    title: "Sort Lines Alphabetically",
    shortDescription: "Sort multiline text in alphabetical order.",
    tags: ["text", "sort", "alphabetical", "lines"],
    intro: "Order lines A-Z for easier review and deduplication.",
    howToUse: ["Paste lines.", "Click Transform.", "Copy sorted result."],
    exampleInput: "zebra\napple\nBanana",
    exampleOutput: "apple\nBanana\nzebra",
    whyUseful: "Useful for organizing keywords, names, and IDs.",
    faq: [
      { question: "Is sorting case-sensitive?", answer: "Sorting is case-insensitive." },
      { question: "Will blank lines stay?", answer: "Yes, blank lines are included in sorting." },
    ],
    related: ["remove-duplicate-lines", "extract-emails", "extract-numbers"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-09",
  },
  {
    slug: "extract-emails",
    title: "Extract Emails from Text",
    shortDescription: "Find and list emails from any text block.",
    tags: ["text", "email", "extract", "parser"],
    intro: "Extract email addresses from logs, documents, or pasted content.",
    howToUse: ["Paste text.", "Click Transform.", "Copy extracted email list."],
    exampleInput: "Contact ana@example.com or bob@site.io",
    exampleOutput: "ana@example.com\nbob@site.io",
    whyUseful: "Speeds up lead cleanup and data extraction tasks.",
    faq: [
      { question: "Are duplicates removed?", answer: "Yes. Output includes unique addresses." },
      { question: "What if none found?", answer: "Tool returns 'No emails found.'" },
    ],
    related: ["extract-numbers", "remove-duplicate-lines", "sort-lines-alphabetically"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-10",
  },
  {
    slug: "extract-numbers",
    title: "Extract Numbers from Text",
    shortDescription: "Pull numeric values from mixed text.",
    tags: ["text", "numbers", "extract", "parser"],
    intro: "Extract decimals and integers from paragraphs, logs, or notes.",
    howToUse: ["Paste text.", "Click Transform.", "Copy extracted numbers."],
    exampleInput: "Order 102, price 49.95, qty 3",
    exampleOutput: "102\n49.95\n3",
    whyUseful: "Quickly isolate numeric values for analysis.",
    faq: [
      { question: "Does it support decimals?", answer: "Yes. Decimal values are extracted." },
      { question: "Are negative numbers supported?", answer: "Yes." },
    ],
    related: ["extract-emails", "remove-duplicate-lines", "sort-lines-alphabetically"],
    kind: "standard",
    categories: ["text-tools"],
    createdAt: "2026-03-11",
  },
];

export const toolsBySlug = Object.fromEntries(tools.map((tool) => [tool.slug, tool]));

export const toolsByCategory = (category: ToolCategorySlug): ToolDefinition[] =>
  tools.filter((tool) => tool.categories.includes(category));

export const recentTools = (limit = 6): ToolDefinition[] =>
  [...tools]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
